CREATE TABLE notes (
    note_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    note_name TEXT NOT NULL,
    content TEXT NOT NULL,
    date_modified TIMESTAMP DEFAULT now() NOT NULL,
    folder_id INTEGER
        REFERENCES folders(folder_id) ON DELETE CASCADE NOT NULL
);
